DROP IF EXISTS BD_VEICULOS;

CREATE TABLE veiculos (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cor VARCHAR(50) NOT NULL,
    ano INT NOT NULL,
    modelo VARCHAR(100) NOT NULL,
    numero_chassi VARCHAR(17) NOT NULL UNIQUE,
    placa VARCHAR(7) NOT NULL UNIQUE,
    unico_dono BOOLEAN NOT NULL DEFAULT FALSE
);

